apiVersion: apps/v1
kind: Deployment
metadata:
  name: tododep001
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tododep001
  template:
    metadata:
      labels:
        app: tododep001
    spec:
      containers:
        - name: todo-container
          image: o2ppo/todoback002:latest # 이미지 이름 확인 필요 (본인 ID 맞는지)
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10      # 스프링 뜰 시간 충분히 부여 (5초 -> 10초)
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080                 # [수정] 정상 작동을 위해 8080으로 변경
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2